#!/usr/bin/env bash
#Displays 1-20 with diff at  4,9 and 17.
num=1
while [ $num -le 20 ]
do
  echo "$num"
  case $num in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((num++))
done
